version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5434:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  server:
    build: ./server
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # Prisma
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/appdb?schema=public"
      # App
      PORT: "3000"
      NODE_ENV: "production"
    ports:
      - "3000:3000"

  client:
    build: ./client
    container_name: web
    depends_on:
      - server
    environment:
      VITE_API_URL: "http://localhost:3000"
    ports:
      - "5173:5173"

volumes:
  pg_data:
