name: tp-projetannuel
region: fra

services:
  - name: app
    source_dir: /
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
      - key: PRISMA_QUERY_ENGINE_LIBRARY
        value: /workspace/server/prisma/generated/client/libquery_engine-debian-openssl-3.0.x.so.node
      - key: PRISMA_QUERY_ENGINE_BINARY
        value: /workspace/server/prisma/generated/client/libquery_engine-debian-openssl-3.0.x.so.node
      - key: PRISMA_CLI_BINARY_TARGETS
        value: debian-openssl-3.0.x,debian-openssl-1.1.x,linux-musl-openssl-3.0.x
    health_check:
      http_path: /health
    routes:
      - path: /

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database

jobs:
  - name: migrate
    source_dir: /server
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
    run_command: npx prisma migrate deploy
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
