name: tp-projet-annuel
services:
  - name: server
    source_dir: /server
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
    http_port: 8080
    routes:
      - path: /api

  - name: client
    source_dir: /client
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
    build_command: npm ci && npm run build && npm install -g serve
    run_command: serve -s dist -l 8080
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: ${server.PUBLIC_URL}/api
    http_port: 8080
    routes:
      - path: /

databases:
  - name: db
    engine: PG
    num_nodes: 1
    size: db-s-dev-database
    version: "16"

jobs:
  - name: db-migrate
    source_dir: /server
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
    build_command: npm ci
    run_command: npx prisma migrate deploy
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
