name: tp-projetannuel
region: fra
services:
  - name: server
    source_dir: /server
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
      deploy_on_push: true
    build_command: npm ci && npx prisma generate && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
    health_check:
      http_path: /health

  - name: client
    source_dir: /client
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
      deploy_on_push: true
    build_command: npm ci && npm run build
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    envs:
      - key: NODE_ENV
        value: production
      - key: VITE_API_URL
        value: ${server.PUBLIC_URL}
      - key: PORT
        value: "8080"
    routes:
      - path: /
    health_check:
      http_path: /

databases:
  - name: db
    engine: PG
    version: "16"
    size: db-s-dev-database

workers:
  - name: migrate
    source_dir: /server
    github:
      repo: Elfspectrals/TP-ProjetAnnuel
      branch: main
    build_command: npm ci && npx prisma generate
    run_command: npx prisma migrate deploy
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}
